#!/bin/sh

# Make sure the the base logging directory exists
mkdir -p /assets/log
cd /usr/flood 
echo "Spawning Flood"

# Execute the binary but with all of its output going
# to a log file.
# >>/var/log/lala  ==> send the stdout to a file openned
#                      as APPEND.
# 2>&1             ==> redirect stderr to whatever stdout
#                      is directed to
exec /usr/flood --host=0.0.0.0 >> /var/log/s6/flood 2>&1
#exec npm start >> /var/log/s6/flood 2>&1
